//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from /work/EasyScript.g4 by ANTLR 4.13.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace EasyAccept.Core.Grammar {
using System;
using System.IO;
using System.Text;
using System.Diagnostics;
using System.Collections.Generic;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.1")]
[System.CLSCompliant(false)]
public partial class EasyScriptParser : Parser {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		EQUAL=1, ECHO_=2, QUIT_=3, EXPECT_=4, EXPECT_ERROR_=5, WORD=6, VARIABLE=7, 
		STRING=8, ENDLINE=9, SPACE=10, COMMENT=11;
	public const int
		RULE_easy = 0, RULE_instruction = 1, RULE_command = 2, RULE_echo_ = 3, 
		RULE_quit_ = 4, RULE_expect_ = 5, RULE_expect_error_ = 6, RULE_unknownCommand = 7, 
		RULE_assignment = 8, RULE_argumentList = 9, RULE_argument = 10, RULE_data = 11;
	public static readonly string[] ruleNames = {
		"easy", "instruction", "command", "echo_", "quit_", "expect_", "expect_error_", 
		"unknownCommand", "assignment", "argumentList", "argument", "data"
	};

	private static readonly string[] _LiteralNames = {
		null, "'='", "'echo'", "'quit'", "'expect'", "'expectError'"
	};
	private static readonly string[] _SymbolicNames = {
		null, "EQUAL", "ECHO_", "QUIT_", "EXPECT_", "EXPECT_ERROR_", "WORD", "VARIABLE", 
		"STRING", "ENDLINE", "SPACE", "COMMENT"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "EasyScript.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override int[] SerializedAtn { get { return _serializedATN; } }

	static EasyScriptParser() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}

		public EasyScriptParser(ITokenStream input) : this(input, Console.Out, Console.Error) { }

		public EasyScriptParser(ITokenStream input, TextWriter output, TextWriter errorOutput)
		: base(input, output, errorOutput)
	{
		Interpreter = new ParserATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	public partial class EasyContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public InstructionContext[] instruction() {
			return GetRuleContexts<InstructionContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public InstructionContext instruction(int i) {
			return GetRuleContext<InstructionContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] ENDLINE() { return GetTokens(EasyScriptParser.ENDLINE); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode ENDLINE(int i) {
			return GetToken(EasyScriptParser.ENDLINE, i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Eof() { return GetToken(EasyScriptParser.Eof, 0); }
		public EasyContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_easy; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IEasyScriptListener typedListener = listener as IEasyScriptListener;
			if (typedListener != null) typedListener.EnterEasy(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IEasyScriptListener typedListener = listener as IEasyScriptListener;
			if (typedListener != null) typedListener.ExitEasy(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IEasyScriptVisitor<TResult> typedVisitor = visitor as IEasyScriptVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitEasy(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public EasyContext easy() {
		EasyContext _localctx = new EasyContext(Context, State);
		EnterRule(_localctx, 0, RULE_easy);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 28;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while ((((_la) & ~0x3f) == 0 && ((1L << _la) & 636L) != 0)) {
				{
				State = 26;
				ErrorHandler.Sync(this);
				switch (TokenStream.LA(1)) {
				case ECHO_:
				case QUIT_:
				case EXPECT_:
				case EXPECT_ERROR_:
				case WORD:
					{
					State = 24;
					instruction();
					}
					break;
				case ENDLINE:
					{
					State = 25;
					Match(ENDLINE);
					}
					break;
				default:
					throw new NoViableAltException(this);
				}
				}
				State = 30;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			State = 32;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,2,Context) ) {
			case 1:
				{
				State = 31;
				Match(Eof);
				}
				break;
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class InstructionContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public CommandContext command() {
			return GetRuleContext<CommandContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode ENDLINE() { return GetToken(EasyScriptParser.ENDLINE, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Eof() { return GetToken(EasyScriptParser.Eof, 0); }
		public InstructionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_instruction; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IEasyScriptListener typedListener = listener as IEasyScriptListener;
			if (typedListener != null) typedListener.EnterInstruction(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IEasyScriptListener typedListener = listener as IEasyScriptListener;
			if (typedListener != null) typedListener.ExitInstruction(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IEasyScriptVisitor<TResult> typedVisitor = visitor as IEasyScriptVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitInstruction(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public InstructionContext instruction() {
		InstructionContext _localctx = new InstructionContext(Context, State);
		EnterRule(_localctx, 2, RULE_instruction);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 34;
			command();
			State = 35;
			_la = TokenStream.LA(1);
			if ( !(_la==Eof || _la==ENDLINE) ) {
			ErrorHandler.RecoverInline(this);
			}
			else {
				ErrorHandler.ReportMatch(this);
			    Consume();
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class CommandContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public Echo_Context echo_() {
			return GetRuleContext<Echo_Context>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public Quit_Context quit_() {
			return GetRuleContext<Quit_Context>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public Expect_Context expect_() {
			return GetRuleContext<Expect_Context>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public Expect_error_Context expect_error_() {
			return GetRuleContext<Expect_error_Context>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public UnknownCommandContext unknownCommand() {
			return GetRuleContext<UnknownCommandContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public AssignmentContext assignment() {
			return GetRuleContext<AssignmentContext>(0);
		}
		public CommandContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_command; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IEasyScriptListener typedListener = listener as IEasyScriptListener;
			if (typedListener != null) typedListener.EnterCommand(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IEasyScriptListener typedListener = listener as IEasyScriptListener;
			if (typedListener != null) typedListener.ExitCommand(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IEasyScriptVisitor<TResult> typedVisitor = visitor as IEasyScriptVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitCommand(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public CommandContext command() {
		CommandContext _localctx = new CommandContext(Context, State);
		EnterRule(_localctx, 4, RULE_command);
		try {
			State = 43;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,3,Context) ) {
			case 1:
				EnterOuterAlt(_localctx, 1);
				{
				State = 37;
				echo_();
				}
				break;
			case 2:
				EnterOuterAlt(_localctx, 2);
				{
				State = 38;
				quit_();
				}
				break;
			case 3:
				EnterOuterAlt(_localctx, 3);
				{
				State = 39;
				expect_();
				}
				break;
			case 4:
				EnterOuterAlt(_localctx, 4);
				{
				State = 40;
				expect_error_();
				}
				break;
			case 5:
				EnterOuterAlt(_localctx, 5);
				{
				State = 41;
				unknownCommand();
				}
				break;
			case 6:
				EnterOuterAlt(_localctx, 6);
				{
				State = 42;
				assignment();
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Echo_Context : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode ECHO_() { return GetToken(EasyScriptParser.ECHO_, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public DataContext data() {
			return GetRuleContext<DataContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] SPACE() { return GetTokens(EasyScriptParser.SPACE); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode SPACE(int i) {
			return GetToken(EasyScriptParser.SPACE, i);
		}
		public Echo_Context(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_echo_; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IEasyScriptListener typedListener = listener as IEasyScriptListener;
			if (typedListener != null) typedListener.EnterEcho_(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IEasyScriptListener typedListener = listener as IEasyScriptListener;
			if (typedListener != null) typedListener.ExitEcho_(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IEasyScriptVisitor<TResult> typedVisitor = visitor as IEasyScriptVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitEcho_(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Echo_Context echo_() {
		Echo_Context _localctx = new Echo_Context(Context, State);
		EnterRule(_localctx, 6, RULE_echo_);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 45;
			Match(ECHO_);
			State = 47;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			do {
				{
				{
				State = 46;
				Match(SPACE);
				}
				}
				State = 49;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			} while ( _la==SPACE );
			State = 51;
			data();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Quit_Context : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode QUIT_() { return GetToken(EasyScriptParser.QUIT_, 0); }
		public Quit_Context(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_quit_; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IEasyScriptListener typedListener = listener as IEasyScriptListener;
			if (typedListener != null) typedListener.EnterQuit_(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IEasyScriptListener typedListener = listener as IEasyScriptListener;
			if (typedListener != null) typedListener.ExitQuit_(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IEasyScriptVisitor<TResult> typedVisitor = visitor as IEasyScriptVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitQuit_(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Quit_Context quit_() {
		Quit_Context _localctx = new Quit_Context(Context, State);
		EnterRule(_localctx, 8, RULE_quit_);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 53;
			Match(QUIT_);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Expect_Context : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode EXPECT_() { return GetToken(EasyScriptParser.EXPECT_, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public DataContext data() {
			return GetRuleContext<DataContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public UnknownCommandContext unknownCommand() {
			return GetRuleContext<UnknownCommandContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] SPACE() { return GetTokens(EasyScriptParser.SPACE); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode SPACE(int i) {
			return GetToken(EasyScriptParser.SPACE, i);
		}
		public Expect_Context(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_expect_; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IEasyScriptListener typedListener = listener as IEasyScriptListener;
			if (typedListener != null) typedListener.EnterExpect_(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IEasyScriptListener typedListener = listener as IEasyScriptListener;
			if (typedListener != null) typedListener.ExitExpect_(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IEasyScriptVisitor<TResult> typedVisitor = visitor as IEasyScriptVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitExpect_(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Expect_Context expect_() {
		Expect_Context _localctx = new Expect_Context(Context, State);
		EnterRule(_localctx, 10, RULE_expect_);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 55;
			Match(EXPECT_);
			State = 57;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			do {
				{
				{
				State = 56;
				Match(SPACE);
				}
				}
				State = 59;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			} while ( _la==SPACE );
			State = 61;
			data();
			State = 63;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			do {
				{
				{
				State = 62;
				Match(SPACE);
				}
				}
				State = 65;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			} while ( _la==SPACE );
			State = 67;
			unknownCommand();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Expect_error_Context : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode EXPECT_ERROR_() { return GetToken(EasyScriptParser.EXPECT_ERROR_, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public DataContext data() {
			return GetRuleContext<DataContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public UnknownCommandContext unknownCommand() {
			return GetRuleContext<UnknownCommandContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] SPACE() { return GetTokens(EasyScriptParser.SPACE); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode SPACE(int i) {
			return GetToken(EasyScriptParser.SPACE, i);
		}
		public Expect_error_Context(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_expect_error_; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IEasyScriptListener typedListener = listener as IEasyScriptListener;
			if (typedListener != null) typedListener.EnterExpect_error_(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IEasyScriptListener typedListener = listener as IEasyScriptListener;
			if (typedListener != null) typedListener.ExitExpect_error_(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IEasyScriptVisitor<TResult> typedVisitor = visitor as IEasyScriptVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitExpect_error_(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Expect_error_Context expect_error_() {
		Expect_error_Context _localctx = new Expect_error_Context(Context, State);
		EnterRule(_localctx, 12, RULE_expect_error_);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 69;
			Match(EXPECT_ERROR_);
			State = 71;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			do {
				{
				{
				State = 70;
				Match(SPACE);
				}
				}
				State = 73;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			} while ( _la==SPACE );
			State = 75;
			data();
			State = 77;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			do {
				{
				{
				State = 76;
				Match(SPACE);
				}
				}
				State = 79;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			} while ( _la==SPACE );
			State = 81;
			unknownCommand();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class UnknownCommandContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode WORD() { return GetToken(EasyScriptParser.WORD, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ArgumentListContext argumentList() {
			return GetRuleContext<ArgumentListContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] SPACE() { return GetTokens(EasyScriptParser.SPACE); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode SPACE(int i) {
			return GetToken(EasyScriptParser.SPACE, i);
		}
		public UnknownCommandContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_unknownCommand; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IEasyScriptListener typedListener = listener as IEasyScriptListener;
			if (typedListener != null) typedListener.EnterUnknownCommand(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IEasyScriptListener typedListener = listener as IEasyScriptListener;
			if (typedListener != null) typedListener.ExitUnknownCommand(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IEasyScriptVisitor<TResult> typedVisitor = visitor as IEasyScriptVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitUnknownCommand(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public UnknownCommandContext unknownCommand() {
		UnknownCommandContext _localctx = new UnknownCommandContext(Context, State);
		EnterRule(_localctx, 14, RULE_unknownCommand);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 83;
			Match(WORD);
			State = 90;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==SPACE) {
				{
				State = 85;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				do {
					{
					{
					State = 84;
					Match(SPACE);
					}
					}
					State = 87;
					ErrorHandler.Sync(this);
					_la = TokenStream.LA(1);
				} while ( _la==SPACE );
				State = 89;
				argumentList();
				}
			}

			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class AssignmentContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode WORD() { return GetToken(EasyScriptParser.WORD, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode EQUAL() { return GetToken(EasyScriptParser.EQUAL, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public UnknownCommandContext unknownCommand() {
			return GetRuleContext<UnknownCommandContext>(0);
		}
		public AssignmentContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_assignment; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IEasyScriptListener typedListener = listener as IEasyScriptListener;
			if (typedListener != null) typedListener.EnterAssignment(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IEasyScriptListener typedListener = listener as IEasyScriptListener;
			if (typedListener != null) typedListener.ExitAssignment(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IEasyScriptVisitor<TResult> typedVisitor = visitor as IEasyScriptVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitAssignment(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public AssignmentContext assignment() {
		AssignmentContext _localctx = new AssignmentContext(Context, State);
		EnterRule(_localctx, 16, RULE_assignment);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 92;
			Match(WORD);
			State = 93;
			Match(EQUAL);
			State = 94;
			unknownCommand();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ArgumentListContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ArgumentContext argument() {
			return GetRuleContext<ArgumentContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ArgumentListContext argumentList() {
			return GetRuleContext<ArgumentListContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] SPACE() { return GetTokens(EasyScriptParser.SPACE); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode SPACE(int i) {
			return GetToken(EasyScriptParser.SPACE, i);
		}
		public ArgumentListContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_argumentList; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IEasyScriptListener typedListener = listener as IEasyScriptListener;
			if (typedListener != null) typedListener.EnterArgumentList(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IEasyScriptListener typedListener = listener as IEasyScriptListener;
			if (typedListener != null) typedListener.ExitArgumentList(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IEasyScriptVisitor<TResult> typedVisitor = visitor as IEasyScriptVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitArgumentList(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ArgumentListContext argumentList() {
		ArgumentListContext _localctx = new ArgumentListContext(Context, State);
		EnterRule(_localctx, 18, RULE_argumentList);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 96;
			argument();
			State = 103;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==SPACE) {
				{
				State = 98;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				do {
					{
					{
					State = 97;
					Match(SPACE);
					}
					}
					State = 100;
					ErrorHandler.Sync(this);
					_la = TokenStream.LA(1);
				} while ( _la==SPACE );
				State = 102;
				argumentList();
				}
			}

			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ArgumentContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode WORD() { return GetToken(EasyScriptParser.WORD, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode EQUAL() { return GetToken(EasyScriptParser.EQUAL, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public DataContext data() {
			return GetRuleContext<DataContext>(0);
		}
		public ArgumentContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_argument; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IEasyScriptListener typedListener = listener as IEasyScriptListener;
			if (typedListener != null) typedListener.EnterArgument(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IEasyScriptListener typedListener = listener as IEasyScriptListener;
			if (typedListener != null) typedListener.ExitArgument(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IEasyScriptVisitor<TResult> typedVisitor = visitor as IEasyScriptVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitArgument(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ArgumentContext argument() {
		ArgumentContext _localctx = new ArgumentContext(Context, State);
		EnterRule(_localctx, 20, RULE_argument);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 105;
			Match(WORD);
			State = 106;
			Match(EQUAL);
			State = 107;
			data();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class DataContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode WORD() { return GetToken(EasyScriptParser.WORD, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode VARIABLE() { return GetToken(EasyScriptParser.VARIABLE, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode STRING() { return GetToken(EasyScriptParser.STRING, 0); }
		public DataContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_data; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IEasyScriptListener typedListener = listener as IEasyScriptListener;
			if (typedListener != null) typedListener.EnterData(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IEasyScriptListener typedListener = listener as IEasyScriptListener;
			if (typedListener != null) typedListener.ExitData(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IEasyScriptVisitor<TResult> typedVisitor = visitor as IEasyScriptVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitData(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public DataContext data() {
		DataContext _localctx = new DataContext(Context, State);
		EnterRule(_localctx, 22, RULE_data);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 109;
			_la = TokenStream.LA(1);
			if ( !((((_la) & ~0x3f) == 0 && ((1L << _la) & 448L) != 0)) ) {
			ErrorHandler.RecoverInline(this);
			}
			else {
				ErrorHandler.ReportMatch(this);
			    Consume();
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	private static int[] _serializedATN = {
		4,1,11,112,2,0,7,0,2,1,7,1,2,2,7,2,2,3,7,3,2,4,7,4,2,5,7,5,2,6,7,6,2,7,
		7,7,2,8,7,8,2,9,7,9,2,10,7,10,2,11,7,11,1,0,1,0,5,0,27,8,0,10,0,12,0,30,
		9,0,1,0,3,0,33,8,0,1,1,1,1,1,1,1,2,1,2,1,2,1,2,1,2,1,2,3,2,44,8,2,1,3,
		1,3,4,3,48,8,3,11,3,12,3,49,1,3,1,3,1,4,1,4,1,5,1,5,4,5,58,8,5,11,5,12,
		5,59,1,5,1,5,4,5,64,8,5,11,5,12,5,65,1,5,1,5,1,6,1,6,4,6,72,8,6,11,6,12,
		6,73,1,6,1,6,4,6,78,8,6,11,6,12,6,79,1,6,1,6,1,7,1,7,4,7,86,8,7,11,7,12,
		7,87,1,7,3,7,91,8,7,1,8,1,8,1,8,1,8,1,9,1,9,4,9,99,8,9,11,9,12,9,100,1,
		9,3,9,104,8,9,1,10,1,10,1,10,1,10,1,11,1,11,1,11,0,0,12,0,2,4,6,8,10,12,
		14,16,18,20,22,0,2,1,1,9,9,1,0,6,8,116,0,28,1,0,0,0,2,34,1,0,0,0,4,43,
		1,0,0,0,6,45,1,0,0,0,8,53,1,0,0,0,10,55,1,0,0,0,12,69,1,0,0,0,14,83,1,
		0,0,0,16,92,1,0,0,0,18,96,1,0,0,0,20,105,1,0,0,0,22,109,1,0,0,0,24,27,
		3,2,1,0,25,27,5,9,0,0,26,24,1,0,0,0,26,25,1,0,0,0,27,30,1,0,0,0,28,26,
		1,0,0,0,28,29,1,0,0,0,29,32,1,0,0,0,30,28,1,0,0,0,31,33,5,0,0,1,32,31,
		1,0,0,0,32,33,1,0,0,0,33,1,1,0,0,0,34,35,3,4,2,0,35,36,7,0,0,0,36,3,1,
		0,0,0,37,44,3,6,3,0,38,44,3,8,4,0,39,44,3,10,5,0,40,44,3,12,6,0,41,44,
		3,14,7,0,42,44,3,16,8,0,43,37,1,0,0,0,43,38,1,0,0,0,43,39,1,0,0,0,43,40,
		1,0,0,0,43,41,1,0,0,0,43,42,1,0,0,0,44,5,1,0,0,0,45,47,5,2,0,0,46,48,5,
		10,0,0,47,46,1,0,0,0,48,49,1,0,0,0,49,47,1,0,0,0,49,50,1,0,0,0,50,51,1,
		0,0,0,51,52,3,22,11,0,52,7,1,0,0,0,53,54,5,3,0,0,54,9,1,0,0,0,55,57,5,
		4,0,0,56,58,5,10,0,0,57,56,1,0,0,0,58,59,1,0,0,0,59,57,1,0,0,0,59,60,1,
		0,0,0,60,61,1,0,0,0,61,63,3,22,11,0,62,64,5,10,0,0,63,62,1,0,0,0,64,65,
		1,0,0,0,65,63,1,0,0,0,65,66,1,0,0,0,66,67,1,0,0,0,67,68,3,14,7,0,68,11,
		1,0,0,0,69,71,5,5,0,0,70,72,5,10,0,0,71,70,1,0,0,0,72,73,1,0,0,0,73,71,
		1,0,0,0,73,74,1,0,0,0,74,75,1,0,0,0,75,77,3,22,11,0,76,78,5,10,0,0,77,
		76,1,0,0,0,78,79,1,0,0,0,79,77,1,0,0,0,79,80,1,0,0,0,80,81,1,0,0,0,81,
		82,3,14,7,0,82,13,1,0,0,0,83,90,5,6,0,0,84,86,5,10,0,0,85,84,1,0,0,0,86,
		87,1,0,0,0,87,85,1,0,0,0,87,88,1,0,0,0,88,89,1,0,0,0,89,91,3,18,9,0,90,
		85,1,0,0,0,90,91,1,0,0,0,91,15,1,0,0,0,92,93,5,6,0,0,93,94,5,1,0,0,94,
		95,3,14,7,0,95,17,1,0,0,0,96,103,3,20,10,0,97,99,5,10,0,0,98,97,1,0,0,
		0,99,100,1,0,0,0,100,98,1,0,0,0,100,101,1,0,0,0,101,102,1,0,0,0,102,104,
		3,18,9,0,103,98,1,0,0,0,103,104,1,0,0,0,104,19,1,0,0,0,105,106,5,6,0,0,
		106,107,5,1,0,0,107,108,3,22,11,0,108,21,1,0,0,0,109,110,7,1,0,0,110,23,
		1,0,0,0,13,26,28,32,43,49,59,65,73,79,87,90,100,103
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
} // namespace EasyAccept.Core.Grammar
