//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from /work/EasyScript.g4 by ANTLR 4.13.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace EasyAccept.Core.Grammar {
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="EasyScriptParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.1")]
[System.CLSCompliant(false)]
public interface IEasyScriptVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="EasyScriptParser.easy"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEasy([NotNull] EasyScriptParser.EasyContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="EasyScriptParser.instruction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInstruction([NotNull] EasyScriptParser.InstructionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="EasyScriptParser.command"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCommand([NotNull] EasyScriptParser.CommandContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="EasyScriptParser.echo_"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEcho_([NotNull] EasyScriptParser.Echo_Context context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="EasyScriptParser.quit_"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitQuit_([NotNull] EasyScriptParser.Quit_Context context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="EasyScriptParser.unknownCommand"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUnknownCommand([NotNull] EasyScriptParser.UnknownCommandContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="EasyScriptParser.argumentList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArgumentList([NotNull] EasyScriptParser.ArgumentListContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="EasyScriptParser.argument"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArgument([NotNull] EasyScriptParser.ArgumentContext context);
}
} // namespace EasyAccept.Core.Grammar
