//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from /work/EasyScript.g4 by ANTLR 4.13.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace EasyAccept.Core.Grammar {

using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="IEasyScriptListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.1")]
[System.Diagnostics.DebuggerNonUserCode]
[System.CLSCompliant(false)]
public partial class EasyScriptBaseListener : IEasyScriptListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="EasyScriptParser.easy"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEasy([NotNull] EasyScriptParser.EasyContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EasyScriptParser.easy"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEasy([NotNull] EasyScriptParser.EasyContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EasyScriptParser.instruction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInstruction([NotNull] EasyScriptParser.InstructionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EasyScriptParser.instruction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInstruction([NotNull] EasyScriptParser.InstructionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EasyScriptParser.command"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCommand([NotNull] EasyScriptParser.CommandContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EasyScriptParser.command"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCommand([NotNull] EasyScriptParser.CommandContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EasyScriptParser.echo_"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEcho_([NotNull] EasyScriptParser.Echo_Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EasyScriptParser.echo_"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEcho_([NotNull] EasyScriptParser.Echo_Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EasyScriptParser.quit_"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterQuit_([NotNull] EasyScriptParser.Quit_Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EasyScriptParser.quit_"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitQuit_([NotNull] EasyScriptParser.Quit_Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EasyScriptParser.expect_"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExpect_([NotNull] EasyScriptParser.Expect_Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EasyScriptParser.expect_"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExpect_([NotNull] EasyScriptParser.Expect_Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EasyScriptParser.expect_different_"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExpect_different_([NotNull] EasyScriptParser.Expect_different_Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EasyScriptParser.expect_different_"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExpect_different_([NotNull] EasyScriptParser.Expect_different_Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EasyScriptParser.expect_error_"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExpect_error_([NotNull] EasyScriptParser.Expect_error_Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EasyScriptParser.expect_error_"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExpect_error_([NotNull] EasyScriptParser.Expect_error_Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EasyScriptParser.unknownCommand"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterUnknownCommand([NotNull] EasyScriptParser.UnknownCommandContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EasyScriptParser.unknownCommand"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitUnknownCommand([NotNull] EasyScriptParser.UnknownCommandContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EasyScriptParser.assignment"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAssignment([NotNull] EasyScriptParser.AssignmentContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EasyScriptParser.assignment"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAssignment([NotNull] EasyScriptParser.AssignmentContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EasyScriptParser.argumentList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterArgumentList([NotNull] EasyScriptParser.ArgumentListContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EasyScriptParser.argumentList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitArgumentList([NotNull] EasyScriptParser.ArgumentListContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EasyScriptParser.argument"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterArgument([NotNull] EasyScriptParser.ArgumentContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EasyScriptParser.argument"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitArgument([NotNull] EasyScriptParser.ArgumentContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EasyScriptParser.data"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterData([NotNull] EasyScriptParser.DataContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EasyScriptParser.data"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitData([NotNull] EasyScriptParser.DataContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
} // namespace EasyAccept.Core.Grammar
