//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from /work/EasyScript.g4 by ANTLR 4.13.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace EasyAccept.Core.Grammar {
using System;
using System.IO;
using System.Text;
using System.Diagnostics;
using System.Collections.Generic;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.1")]
[System.CLSCompliant(false)]
public partial class EasyScriptParser : Parser {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		EQUAL=1, ECHO_=2, QUIT_=3, EXPECT_=4, EXPECT_ERROR_=5, WORD=6, STRING=7, 
		ENDLINE=8, SPACE=9, COMMENT=10;
	public const int
		RULE_easy = 0, RULE_instruction = 1, RULE_command = 2, RULE_echo_ = 3, 
		RULE_quit_ = 4, RULE_expect_ = 5, RULE_expect_error_ = 6, RULE_unknownCommand = 7, 
		RULE_argumentList = 8, RULE_argument = 9;
	public static readonly string[] ruleNames = {
		"easy", "instruction", "command", "echo_", "quit_", "expect_", "expect_error_", 
		"unknownCommand", "argumentList", "argument"
	};

	private static readonly string[] _LiteralNames = {
		null, "'='", "'echo'", "'quit'", "'expect'", "'expectError'"
	};
	private static readonly string[] _SymbolicNames = {
		null, "EQUAL", "ECHO_", "QUIT_", "EXPECT_", "EXPECT_ERROR_", "WORD", "STRING", 
		"ENDLINE", "SPACE", "COMMENT"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "EasyScript.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override int[] SerializedAtn { get { return _serializedATN; } }

	static EasyScriptParser() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}

		public EasyScriptParser(ITokenStream input) : this(input, Console.Out, Console.Error) { }

		public EasyScriptParser(ITokenStream input, TextWriter output, TextWriter errorOutput)
		: base(input, output, errorOutput)
	{
		Interpreter = new ParserATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	public partial class EasyContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public InstructionContext[] instruction() {
			return GetRuleContexts<InstructionContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public InstructionContext instruction(int i) {
			return GetRuleContext<InstructionContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] ENDLINE() { return GetTokens(EasyScriptParser.ENDLINE); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode ENDLINE(int i) {
			return GetToken(EasyScriptParser.ENDLINE, i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Eof() { return GetToken(EasyScriptParser.Eof, 0); }
		public EasyContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_easy; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IEasyScriptVisitor<TResult> typedVisitor = visitor as IEasyScriptVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitEasy(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public EasyContext easy() {
		EasyContext _localctx = new EasyContext(Context, State);
		EnterRule(_localctx, 0, RULE_easy);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 24;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while ((((_la) & ~0x3f) == 0 && ((1L << _la) & 380L) != 0)) {
				{
				State = 22;
				ErrorHandler.Sync(this);
				switch (TokenStream.LA(1)) {
				case ECHO_:
				case QUIT_:
				case EXPECT_:
				case EXPECT_ERROR_:
				case WORD:
					{
					State = 20;
					instruction();
					}
					break;
				case ENDLINE:
					{
					State = 21;
					Match(ENDLINE);
					}
					break;
				default:
					throw new NoViableAltException(this);
				}
				}
				State = 26;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			State = 28;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,2,Context) ) {
			case 1:
				{
				State = 27;
				Match(Eof);
				}
				break;
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class InstructionContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public CommandContext command() {
			return GetRuleContext<CommandContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode ENDLINE() { return GetToken(EasyScriptParser.ENDLINE, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Eof() { return GetToken(EasyScriptParser.Eof, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] SPACE() { return GetTokens(EasyScriptParser.SPACE); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode SPACE(int i) {
			return GetToken(EasyScriptParser.SPACE, i);
		}
		public InstructionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_instruction; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IEasyScriptVisitor<TResult> typedVisitor = visitor as IEasyScriptVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitInstruction(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public InstructionContext instruction() {
		InstructionContext _localctx = new InstructionContext(Context, State);
		EnterRule(_localctx, 2, RULE_instruction);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 30;
			command();
			State = 34;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==SPACE) {
				{
				{
				State = 31;
				Match(SPACE);
				}
				}
				State = 36;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			State = 37;
			_la = TokenStream.LA(1);
			if ( !(_la==Eof || _la==ENDLINE) ) {
			ErrorHandler.RecoverInline(this);
			}
			else {
				ErrorHandler.ReportMatch(this);
			    Consume();
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class CommandContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public Echo_Context echo_() {
			return GetRuleContext<Echo_Context>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public Quit_Context quit_() {
			return GetRuleContext<Quit_Context>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public Expect_Context expect_() {
			return GetRuleContext<Expect_Context>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public Expect_error_Context expect_error_() {
			return GetRuleContext<Expect_error_Context>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public UnknownCommandContext unknownCommand() {
			return GetRuleContext<UnknownCommandContext>(0);
		}
		public CommandContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_command; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IEasyScriptVisitor<TResult> typedVisitor = visitor as IEasyScriptVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitCommand(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public CommandContext command() {
		CommandContext _localctx = new CommandContext(Context, State);
		EnterRule(_localctx, 4, RULE_command);
		try {
			State = 44;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case ECHO_:
				EnterOuterAlt(_localctx, 1);
				{
				State = 39;
				echo_();
				}
				break;
			case QUIT_:
				EnterOuterAlt(_localctx, 2);
				{
				State = 40;
				quit_();
				}
				break;
			case EXPECT_:
				EnterOuterAlt(_localctx, 3);
				{
				State = 41;
				expect_();
				}
				break;
			case EXPECT_ERROR_:
				EnterOuterAlt(_localctx, 4);
				{
				State = 42;
				expect_error_();
				}
				break;
			case WORD:
				EnterOuterAlt(_localctx, 5);
				{
				State = 43;
				unknownCommand();
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Echo_Context : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode ECHO_() { return GetToken(EasyScriptParser.ECHO_, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode STRING() { return GetToken(EasyScriptParser.STRING, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] SPACE() { return GetTokens(EasyScriptParser.SPACE); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode SPACE(int i) {
			return GetToken(EasyScriptParser.SPACE, i);
		}
		public Echo_Context(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_echo_; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IEasyScriptVisitor<TResult> typedVisitor = visitor as IEasyScriptVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitEcho_(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Echo_Context echo_() {
		Echo_Context _localctx = new Echo_Context(Context, State);
		EnterRule(_localctx, 6, RULE_echo_);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 46;
			Match(ECHO_);
			State = 48;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			do {
				{
				{
				State = 47;
				Match(SPACE);
				}
				}
				State = 50;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			} while ( _la==SPACE );
			State = 52;
			Match(STRING);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Quit_Context : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode QUIT_() { return GetToken(EasyScriptParser.QUIT_, 0); }
		public Quit_Context(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_quit_; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IEasyScriptVisitor<TResult> typedVisitor = visitor as IEasyScriptVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitQuit_(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Quit_Context quit_() {
		Quit_Context _localctx = new Quit_Context(Context, State);
		EnterRule(_localctx, 8, RULE_quit_);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 54;
			Match(QUIT_);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Expect_Context : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode EXPECT_() { return GetToken(EasyScriptParser.EXPECT_, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public UnknownCommandContext unknownCommand() {
			return GetRuleContext<UnknownCommandContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode WORD() { return GetToken(EasyScriptParser.WORD, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode STRING() { return GetToken(EasyScriptParser.STRING, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] SPACE() { return GetTokens(EasyScriptParser.SPACE); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode SPACE(int i) {
			return GetToken(EasyScriptParser.SPACE, i);
		}
		public Expect_Context(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_expect_; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IEasyScriptVisitor<TResult> typedVisitor = visitor as IEasyScriptVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitExpect_(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Expect_Context expect_() {
		Expect_Context _localctx = new Expect_Context(Context, State);
		EnterRule(_localctx, 10, RULE_expect_);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 56;
			Match(EXPECT_);
			State = 58;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			do {
				{
				{
				State = 57;
				Match(SPACE);
				}
				}
				State = 60;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			} while ( _la==SPACE );
			State = 62;
			_la = TokenStream.LA(1);
			if ( !(_la==WORD || _la==STRING) ) {
			ErrorHandler.RecoverInline(this);
			}
			else {
				ErrorHandler.ReportMatch(this);
			    Consume();
			}
			State = 64;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			do {
				{
				{
				State = 63;
				Match(SPACE);
				}
				}
				State = 66;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			} while ( _la==SPACE );
			State = 68;
			unknownCommand();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Expect_error_Context : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode EXPECT_ERROR_() { return GetToken(EasyScriptParser.EXPECT_ERROR_, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public UnknownCommandContext unknownCommand() {
			return GetRuleContext<UnknownCommandContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode WORD() { return GetToken(EasyScriptParser.WORD, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode STRING() { return GetToken(EasyScriptParser.STRING, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] SPACE() { return GetTokens(EasyScriptParser.SPACE); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode SPACE(int i) {
			return GetToken(EasyScriptParser.SPACE, i);
		}
		public Expect_error_Context(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_expect_error_; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IEasyScriptVisitor<TResult> typedVisitor = visitor as IEasyScriptVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitExpect_error_(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Expect_error_Context expect_error_() {
		Expect_error_Context _localctx = new Expect_error_Context(Context, State);
		EnterRule(_localctx, 12, RULE_expect_error_);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 70;
			Match(EXPECT_ERROR_);
			State = 72;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			do {
				{
				{
				State = 71;
				Match(SPACE);
				}
				}
				State = 74;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			} while ( _la==SPACE );
			State = 76;
			_la = TokenStream.LA(1);
			if ( !(_la==WORD || _la==STRING) ) {
			ErrorHandler.RecoverInline(this);
			}
			else {
				ErrorHandler.ReportMatch(this);
			    Consume();
			}
			State = 78;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			do {
				{
				{
				State = 77;
				Match(SPACE);
				}
				}
				State = 80;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			} while ( _la==SPACE );
			State = 82;
			unknownCommand();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class UnknownCommandContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode WORD() { return GetToken(EasyScriptParser.WORD, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ArgumentListContext argumentList() {
			return GetRuleContext<ArgumentListContext>(0);
		}
		public UnknownCommandContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_unknownCommand; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IEasyScriptVisitor<TResult> typedVisitor = visitor as IEasyScriptVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitUnknownCommand(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public UnknownCommandContext unknownCommand() {
		UnknownCommandContext _localctx = new UnknownCommandContext(Context, State);
		EnterRule(_localctx, 14, RULE_unknownCommand);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 84;
			Match(WORD);
			State = 86;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==WORD) {
				{
				State = 85;
				argumentList();
				}
			}

			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ArgumentListContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ArgumentContext argument() {
			return GetRuleContext<ArgumentContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ArgumentListContext argumentList() {
			return GetRuleContext<ArgumentListContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] SPACE() { return GetTokens(EasyScriptParser.SPACE); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode SPACE(int i) {
			return GetToken(EasyScriptParser.SPACE, i);
		}
		public ArgumentListContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_argumentList; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IEasyScriptVisitor<TResult> typedVisitor = visitor as IEasyScriptVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitArgumentList(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ArgumentListContext argumentList() {
		ArgumentListContext _localctx = new ArgumentListContext(Context, State);
		EnterRule(_localctx, 16, RULE_argumentList);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 88;
			argument();
			State = 95;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,12,Context) ) {
			case 1:
				{
				State = 90;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				do {
					{
					{
					State = 89;
					Match(SPACE);
					}
					}
					State = 92;
					ErrorHandler.Sync(this);
					_la = TokenStream.LA(1);
				} while ( _la==SPACE );
				State = 94;
				argumentList();
				}
				break;
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ArgumentContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] WORD() { return GetTokens(EasyScriptParser.WORD); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode WORD(int i) {
			return GetToken(EasyScriptParser.WORD, i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode EQUAL() { return GetToken(EasyScriptParser.EQUAL, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode STRING() { return GetToken(EasyScriptParser.STRING, 0); }
		public ArgumentContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_argument; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IEasyScriptVisitor<TResult> typedVisitor = visitor as IEasyScriptVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitArgument(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ArgumentContext argument() {
		ArgumentContext _localctx = new ArgumentContext(Context, State);
		EnterRule(_localctx, 18, RULE_argument);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 97;
			Match(WORD);
			State = 98;
			Match(EQUAL);
			State = 99;
			_la = TokenStream.LA(1);
			if ( !(_la==WORD || _la==STRING) ) {
			ErrorHandler.RecoverInline(this);
			}
			else {
				ErrorHandler.ReportMatch(this);
			    Consume();
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	private static int[] _serializedATN = {
		4,1,10,102,2,0,7,0,2,1,7,1,2,2,7,2,2,3,7,3,2,4,7,4,2,5,7,5,2,6,7,6,2,7,
		7,7,2,8,7,8,2,9,7,9,1,0,1,0,5,0,23,8,0,10,0,12,0,26,9,0,1,0,3,0,29,8,0,
		1,1,1,1,5,1,33,8,1,10,1,12,1,36,9,1,1,1,1,1,1,2,1,2,1,2,1,2,1,2,3,2,45,
		8,2,1,3,1,3,4,3,49,8,3,11,3,12,3,50,1,3,1,3,1,4,1,4,1,5,1,5,4,5,59,8,5,
		11,5,12,5,60,1,5,1,5,4,5,65,8,5,11,5,12,5,66,1,5,1,5,1,6,1,6,4,6,73,8,
		6,11,6,12,6,74,1,6,1,6,4,6,79,8,6,11,6,12,6,80,1,6,1,6,1,7,1,7,3,7,87,
		8,7,1,8,1,8,4,8,91,8,8,11,8,12,8,92,1,8,3,8,96,8,8,1,9,1,9,1,9,1,9,1,9,
		0,0,10,0,2,4,6,8,10,12,14,16,18,0,2,1,1,8,8,1,0,6,7,107,0,24,1,0,0,0,2,
		30,1,0,0,0,4,44,1,0,0,0,6,46,1,0,0,0,8,54,1,0,0,0,10,56,1,0,0,0,12,70,
		1,0,0,0,14,84,1,0,0,0,16,88,1,0,0,0,18,97,1,0,0,0,20,23,3,2,1,0,21,23,
		5,8,0,0,22,20,1,0,0,0,22,21,1,0,0,0,23,26,1,0,0,0,24,22,1,0,0,0,24,25,
		1,0,0,0,25,28,1,0,0,0,26,24,1,0,0,0,27,29,5,0,0,1,28,27,1,0,0,0,28,29,
		1,0,0,0,29,1,1,0,0,0,30,34,3,4,2,0,31,33,5,9,0,0,32,31,1,0,0,0,33,36,1,
		0,0,0,34,32,1,0,0,0,34,35,1,0,0,0,35,37,1,0,0,0,36,34,1,0,0,0,37,38,7,
		0,0,0,38,3,1,0,0,0,39,45,3,6,3,0,40,45,3,8,4,0,41,45,3,10,5,0,42,45,3,
		12,6,0,43,45,3,14,7,0,44,39,1,0,0,0,44,40,1,0,0,0,44,41,1,0,0,0,44,42,
		1,0,0,0,44,43,1,0,0,0,45,5,1,0,0,0,46,48,5,2,0,0,47,49,5,9,0,0,48,47,1,
		0,0,0,49,50,1,0,0,0,50,48,1,0,0,0,50,51,1,0,0,0,51,52,1,0,0,0,52,53,5,
		7,0,0,53,7,1,0,0,0,54,55,5,3,0,0,55,9,1,0,0,0,56,58,5,4,0,0,57,59,5,9,
		0,0,58,57,1,0,0,0,59,60,1,0,0,0,60,58,1,0,0,0,60,61,1,0,0,0,61,62,1,0,
		0,0,62,64,7,1,0,0,63,65,5,9,0,0,64,63,1,0,0,0,65,66,1,0,0,0,66,64,1,0,
		0,0,66,67,1,0,0,0,67,68,1,0,0,0,68,69,3,14,7,0,69,11,1,0,0,0,70,72,5,5,
		0,0,71,73,5,9,0,0,72,71,1,0,0,0,73,74,1,0,0,0,74,72,1,0,0,0,74,75,1,0,
		0,0,75,76,1,0,0,0,76,78,7,1,0,0,77,79,5,9,0,0,78,77,1,0,0,0,79,80,1,0,
		0,0,80,78,1,0,0,0,80,81,1,0,0,0,81,82,1,0,0,0,82,83,3,14,7,0,83,13,1,0,
		0,0,84,86,5,6,0,0,85,87,3,16,8,0,86,85,1,0,0,0,86,87,1,0,0,0,87,15,1,0,
		0,0,88,95,3,18,9,0,89,91,5,9,0,0,90,89,1,0,0,0,91,92,1,0,0,0,92,90,1,0,
		0,0,92,93,1,0,0,0,93,94,1,0,0,0,94,96,3,16,8,0,95,90,1,0,0,0,95,96,1,0,
		0,0,96,17,1,0,0,0,97,98,5,6,0,0,98,99,5,1,0,0,99,100,7,1,0,0,100,19,1,
		0,0,0,13,22,24,28,34,44,50,60,66,74,80,86,92,95
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
} // namespace EasyAccept.Core.Grammar
