//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from /work/EasyScript.g4 by ANTLR 4.13.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace EasyAccept.Core.Grammar {
using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="EasyScriptParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.1")]
[System.CLSCompliant(false)]
public interface IEasyScriptListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="EasyScriptParser.easy"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEasy([NotNull] EasyScriptParser.EasyContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="EasyScriptParser.easy"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEasy([NotNull] EasyScriptParser.EasyContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="EasyScriptParser.instruction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInstruction([NotNull] EasyScriptParser.InstructionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="EasyScriptParser.instruction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInstruction([NotNull] EasyScriptParser.InstructionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="EasyScriptParser.command"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCommand([NotNull] EasyScriptParser.CommandContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="EasyScriptParser.command"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCommand([NotNull] EasyScriptParser.CommandContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="EasyScriptParser.echo_"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEcho_([NotNull] EasyScriptParser.Echo_Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="EasyScriptParser.echo_"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEcho_([NotNull] EasyScriptParser.Echo_Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="EasyScriptParser.quit_"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterQuit_([NotNull] EasyScriptParser.Quit_Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="EasyScriptParser.quit_"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitQuit_([NotNull] EasyScriptParser.Quit_Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="EasyScriptParser.expect_"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpect_([NotNull] EasyScriptParser.Expect_Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="EasyScriptParser.expect_"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpect_([NotNull] EasyScriptParser.Expect_Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="EasyScriptParser.expect_different_"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpect_different_([NotNull] EasyScriptParser.Expect_different_Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="EasyScriptParser.expect_different_"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpect_different_([NotNull] EasyScriptParser.Expect_different_Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="EasyScriptParser.expect_error_"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpect_error_([NotNull] EasyScriptParser.Expect_error_Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="EasyScriptParser.expect_error_"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpect_error_([NotNull] EasyScriptParser.Expect_error_Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="EasyScriptParser.unknownCommand"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterUnknownCommand([NotNull] EasyScriptParser.UnknownCommandContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="EasyScriptParser.unknownCommand"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitUnknownCommand([NotNull] EasyScriptParser.UnknownCommandContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="EasyScriptParser.assignment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAssignment([NotNull] EasyScriptParser.AssignmentContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="EasyScriptParser.assignment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAssignment([NotNull] EasyScriptParser.AssignmentContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="EasyScriptParser.argumentList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterArgumentList([NotNull] EasyScriptParser.ArgumentListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="EasyScriptParser.argumentList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitArgumentList([NotNull] EasyScriptParser.ArgumentListContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="EasyScriptParser.argument"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterArgument([NotNull] EasyScriptParser.ArgumentContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="EasyScriptParser.argument"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitArgument([NotNull] EasyScriptParser.ArgumentContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="EasyScriptParser.data"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterData([NotNull] EasyScriptParser.DataContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="EasyScriptParser.data"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitData([NotNull] EasyScriptParser.DataContext context);
}
} // namespace EasyAccept.Core.Grammar
