//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from /work/EasyScript.g4 by ANTLR 4.13.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace EasyAccept.Core.Grammar {
using System;
using System.IO;
using System.Text;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.1")]
[System.CLSCompliant(false)]
public partial class EasyScriptLexer : Lexer {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		EQUAL=1, ECHO_=2, QUIT_=3, EXPECT_=4, WORD=5, STRING=6, ENDLINE=7, SPACE=8, 
		COMMENT=9;
	public static string[] channelNames = {
		"DEFAULT_TOKEN_CHANNEL", "HIDDEN"
	};

	public static string[] modeNames = {
		"DEFAULT_MODE"
	};

	public static readonly string[] ruleNames = {
		"EQUAL", "ECHO_", "QUIT_", "EXPECT_", "WORD", "STRING", "ENDLINE", "SPACE", 
		"COMMENT"
	};


	public EasyScriptLexer(ICharStream input)
	: this(input, Console.Out, Console.Error) { }

	public EasyScriptLexer(ICharStream input, TextWriter output, TextWriter errorOutput)
	: base(input, output, errorOutput)
	{
		Interpreter = new LexerATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	private static readonly string[] _LiteralNames = {
		null, "'='", "'echo'", "'quit'", "'expect'"
	};
	private static readonly string[] _SymbolicNames = {
		null, "EQUAL", "ECHO_", "QUIT_", "EXPECT_", "WORD", "STRING", "ENDLINE", 
		"SPACE", "COMMENT"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "EasyScript.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override string[] ChannelNames { get { return channelNames; } }

	public override string[] ModeNames { get { return modeNames; } }

	public override int[] SerializedAtn { get { return _serializedATN; } }

	static EasyScriptLexer() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}
	private static int[] _serializedATN = {
		4,0,9,87,6,-1,2,0,7,0,2,1,7,1,2,2,7,2,2,3,7,3,2,4,7,4,2,5,7,5,2,6,7,6,
		2,7,7,7,2,8,7,8,1,0,1,0,1,1,1,1,1,1,1,1,1,1,1,2,1,2,1,2,1,2,1,2,1,3,1,
		3,1,3,1,3,1,3,1,3,1,3,1,4,4,4,40,8,4,11,4,12,4,41,1,5,1,5,5,5,46,8,5,10,
		5,12,5,49,9,5,1,5,1,5,1,5,5,5,54,8,5,10,5,12,5,57,9,5,1,5,3,5,60,8,5,1,
		6,5,6,63,8,6,10,6,12,6,66,9,6,1,6,3,6,69,8,6,1,6,1,6,1,7,1,7,1,8,1,8,5,
		8,77,8,8,10,8,12,8,80,9,8,1,8,1,8,3,8,84,8,8,1,8,1,8,0,0,9,1,1,3,2,5,3,
		7,4,9,5,11,6,13,7,15,8,17,9,1,0,4,5,0,9,10,13,13,32,32,34,34,39,39,2,0,
		34,34,39,39,2,0,9,9,32,32,2,0,10,10,13,13,94,0,1,1,0,0,0,0,3,1,0,0,0,0,
		5,1,0,0,0,0,7,1,0,0,0,0,9,1,0,0,0,0,11,1,0,0,0,0,13,1,0,0,0,0,15,1,0,0,
		0,0,17,1,0,0,0,1,19,1,0,0,0,3,21,1,0,0,0,5,26,1,0,0,0,7,31,1,0,0,0,9,39,
		1,0,0,0,11,59,1,0,0,0,13,64,1,0,0,0,15,72,1,0,0,0,17,74,1,0,0,0,19,20,
		5,61,0,0,20,2,1,0,0,0,21,22,5,101,0,0,22,23,5,99,0,0,23,24,5,104,0,0,24,
		25,5,111,0,0,25,4,1,0,0,0,26,27,5,113,0,0,27,28,5,117,0,0,28,29,5,105,
		0,0,29,30,5,116,0,0,30,6,1,0,0,0,31,32,5,101,0,0,32,33,5,120,0,0,33,34,
		5,112,0,0,34,35,5,101,0,0,35,36,5,99,0,0,36,37,5,116,0,0,37,8,1,0,0,0,
		38,40,8,0,0,0,39,38,1,0,0,0,40,41,1,0,0,0,41,39,1,0,0,0,41,42,1,0,0,0,
		42,10,1,0,0,0,43,47,5,34,0,0,44,46,8,1,0,0,45,44,1,0,0,0,46,49,1,0,0,0,
		47,45,1,0,0,0,47,48,1,0,0,0,48,50,1,0,0,0,49,47,1,0,0,0,50,60,5,34,0,0,
		51,55,5,39,0,0,52,54,8,1,0,0,53,52,1,0,0,0,54,57,1,0,0,0,55,53,1,0,0,0,
		55,56,1,0,0,0,56,58,1,0,0,0,57,55,1,0,0,0,58,60,5,39,0,0,59,43,1,0,0,0,
		59,51,1,0,0,0,60,12,1,0,0,0,61,63,3,15,7,0,62,61,1,0,0,0,63,66,1,0,0,0,
		64,62,1,0,0,0,64,65,1,0,0,0,65,68,1,0,0,0,66,64,1,0,0,0,67,69,5,13,0,0,
		68,67,1,0,0,0,68,69,1,0,0,0,69,70,1,0,0,0,70,71,5,10,0,0,71,14,1,0,0,0,
		72,73,7,2,0,0,73,16,1,0,0,0,74,78,5,35,0,0,75,77,8,3,0,0,76,75,1,0,0,0,
		77,80,1,0,0,0,78,76,1,0,0,0,78,79,1,0,0,0,79,83,1,0,0,0,80,78,1,0,0,0,
		81,84,3,13,6,0,82,84,5,0,0,1,83,81,1,0,0,0,83,82,1,0,0,0,84,85,1,0,0,0,
		85,86,6,8,0,0,86,18,1,0,0,0,9,0,41,47,55,59,64,68,78,83,1,6,0,0
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
} // namespace EasyAccept.Core.Grammar
