//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from /work/EasyScript.g4 by ANTLR 4.13.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace EasyAccept.Core.Grammar {
using System;
using System.IO;
using System.Text;
using System.Diagnostics;
using System.Collections.Generic;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.1")]
[System.CLSCompliant(false)]
public partial class EasyScriptParser : Parser {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		EQUAL=1, ECHO_=2, QUIT_=3, EXPECT_=4, EXPECT_ERROR_=5, WORD=6, VARIABLE=7, 
		STRING=8, ENDLINE=9, SPACE=10, COMMENT=11;
	public const int
		RULE_easy = 0, RULE_instruction = 1, RULE_command = 2, RULE_echo_ = 3, 
		RULE_quit_ = 4, RULE_expect_ = 5, RULE_expect_error_ = 6, RULE_unknownCommand = 7, 
		RULE_assignment = 8, RULE_argumentList = 9, RULE_argument = 10;
	public static readonly string[] ruleNames = {
		"easy", "instruction", "command", "echo_", "quit_", "expect_", "expect_error_", 
		"unknownCommand", "assignment", "argumentList", "argument"
	};

	private static readonly string[] _LiteralNames = {
		null, "'='", "'echo'", "'quit'", "'expect'", "'expectError'"
	};
	private static readonly string[] _SymbolicNames = {
		null, "EQUAL", "ECHO_", "QUIT_", "EXPECT_", "EXPECT_ERROR_", "WORD", "VARIABLE", 
		"STRING", "ENDLINE", "SPACE", "COMMENT"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "EasyScript.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override int[] SerializedAtn { get { return _serializedATN; } }

	static EasyScriptParser() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}

		public EasyScriptParser(ITokenStream input) : this(input, Console.Out, Console.Error) { }

		public EasyScriptParser(ITokenStream input, TextWriter output, TextWriter errorOutput)
		: base(input, output, errorOutput)
	{
		Interpreter = new ParserATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	public partial class EasyContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public InstructionContext[] instruction() {
			return GetRuleContexts<InstructionContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public InstructionContext instruction(int i) {
			return GetRuleContext<InstructionContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] ENDLINE() { return GetTokens(EasyScriptParser.ENDLINE); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode ENDLINE(int i) {
			return GetToken(EasyScriptParser.ENDLINE, i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Eof() { return GetToken(EasyScriptParser.Eof, 0); }
		public EasyContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_easy; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IEasyScriptListener typedListener = listener as IEasyScriptListener;
			if (typedListener != null) typedListener.EnterEasy(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IEasyScriptListener typedListener = listener as IEasyScriptListener;
			if (typedListener != null) typedListener.ExitEasy(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IEasyScriptVisitor<TResult> typedVisitor = visitor as IEasyScriptVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitEasy(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public EasyContext easy() {
		EasyContext _localctx = new EasyContext(Context, State);
		EnterRule(_localctx, 0, RULE_easy);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 26;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while ((((_la) & ~0x3f) == 0 && ((1L << _la) & 636L) != 0)) {
				{
				State = 24;
				ErrorHandler.Sync(this);
				switch (TokenStream.LA(1)) {
				case ECHO_:
				case QUIT_:
				case EXPECT_:
				case EXPECT_ERROR_:
				case WORD:
					{
					State = 22;
					instruction();
					}
					break;
				case ENDLINE:
					{
					State = 23;
					Match(ENDLINE);
					}
					break;
				default:
					throw new NoViableAltException(this);
				}
				}
				State = 28;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			State = 30;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,2,Context) ) {
			case 1:
				{
				State = 29;
				Match(Eof);
				}
				break;
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class InstructionContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public CommandContext command() {
			return GetRuleContext<CommandContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode ENDLINE() { return GetToken(EasyScriptParser.ENDLINE, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Eof() { return GetToken(EasyScriptParser.Eof, 0); }
		public InstructionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_instruction; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IEasyScriptListener typedListener = listener as IEasyScriptListener;
			if (typedListener != null) typedListener.EnterInstruction(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IEasyScriptListener typedListener = listener as IEasyScriptListener;
			if (typedListener != null) typedListener.ExitInstruction(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IEasyScriptVisitor<TResult> typedVisitor = visitor as IEasyScriptVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitInstruction(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public InstructionContext instruction() {
		InstructionContext _localctx = new InstructionContext(Context, State);
		EnterRule(_localctx, 2, RULE_instruction);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 32;
			command();
			State = 33;
			_la = TokenStream.LA(1);
			if ( !(_la==Eof || _la==ENDLINE) ) {
			ErrorHandler.RecoverInline(this);
			}
			else {
				ErrorHandler.ReportMatch(this);
			    Consume();
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class CommandContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public Echo_Context echo_() {
			return GetRuleContext<Echo_Context>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public Quit_Context quit_() {
			return GetRuleContext<Quit_Context>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public Expect_Context expect_() {
			return GetRuleContext<Expect_Context>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public Expect_error_Context expect_error_() {
			return GetRuleContext<Expect_error_Context>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public UnknownCommandContext unknownCommand() {
			return GetRuleContext<UnknownCommandContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public AssignmentContext assignment() {
			return GetRuleContext<AssignmentContext>(0);
		}
		public CommandContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_command; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IEasyScriptListener typedListener = listener as IEasyScriptListener;
			if (typedListener != null) typedListener.EnterCommand(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IEasyScriptListener typedListener = listener as IEasyScriptListener;
			if (typedListener != null) typedListener.ExitCommand(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IEasyScriptVisitor<TResult> typedVisitor = visitor as IEasyScriptVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitCommand(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public CommandContext command() {
		CommandContext _localctx = new CommandContext(Context, State);
		EnterRule(_localctx, 4, RULE_command);
		try {
			State = 41;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,3,Context) ) {
			case 1:
				EnterOuterAlt(_localctx, 1);
				{
				State = 35;
				echo_();
				}
				break;
			case 2:
				EnterOuterAlt(_localctx, 2);
				{
				State = 36;
				quit_();
				}
				break;
			case 3:
				EnterOuterAlt(_localctx, 3);
				{
				State = 37;
				expect_();
				}
				break;
			case 4:
				EnterOuterAlt(_localctx, 4);
				{
				State = 38;
				expect_error_();
				}
				break;
			case 5:
				EnterOuterAlt(_localctx, 5);
				{
				State = 39;
				unknownCommand();
				}
				break;
			case 6:
				EnterOuterAlt(_localctx, 6);
				{
				State = 40;
				assignment();
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Echo_Context : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode ECHO_() { return GetToken(EasyScriptParser.ECHO_, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode WORD() { return GetToken(EasyScriptParser.WORD, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode VARIABLE() { return GetToken(EasyScriptParser.VARIABLE, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode STRING() { return GetToken(EasyScriptParser.STRING, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] SPACE() { return GetTokens(EasyScriptParser.SPACE); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode SPACE(int i) {
			return GetToken(EasyScriptParser.SPACE, i);
		}
		public Echo_Context(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_echo_; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IEasyScriptListener typedListener = listener as IEasyScriptListener;
			if (typedListener != null) typedListener.EnterEcho_(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IEasyScriptListener typedListener = listener as IEasyScriptListener;
			if (typedListener != null) typedListener.ExitEcho_(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IEasyScriptVisitor<TResult> typedVisitor = visitor as IEasyScriptVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitEcho_(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Echo_Context echo_() {
		Echo_Context _localctx = new Echo_Context(Context, State);
		EnterRule(_localctx, 6, RULE_echo_);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 43;
			Match(ECHO_);
			State = 45;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			do {
				{
				{
				State = 44;
				Match(SPACE);
				}
				}
				State = 47;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			} while ( _la==SPACE );
			State = 49;
			_la = TokenStream.LA(1);
			if ( !((((_la) & ~0x3f) == 0 && ((1L << _la) & 448L) != 0)) ) {
			ErrorHandler.RecoverInline(this);
			}
			else {
				ErrorHandler.ReportMatch(this);
			    Consume();
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Quit_Context : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode QUIT_() { return GetToken(EasyScriptParser.QUIT_, 0); }
		public Quit_Context(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_quit_; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IEasyScriptListener typedListener = listener as IEasyScriptListener;
			if (typedListener != null) typedListener.EnterQuit_(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IEasyScriptListener typedListener = listener as IEasyScriptListener;
			if (typedListener != null) typedListener.ExitQuit_(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IEasyScriptVisitor<TResult> typedVisitor = visitor as IEasyScriptVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitQuit_(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Quit_Context quit_() {
		Quit_Context _localctx = new Quit_Context(Context, State);
		EnterRule(_localctx, 8, RULE_quit_);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 51;
			Match(QUIT_);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Expect_Context : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode EXPECT_() { return GetToken(EasyScriptParser.EXPECT_, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public UnknownCommandContext unknownCommand() {
			return GetRuleContext<UnknownCommandContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode WORD() { return GetToken(EasyScriptParser.WORD, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode VARIABLE() { return GetToken(EasyScriptParser.VARIABLE, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode STRING() { return GetToken(EasyScriptParser.STRING, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] SPACE() { return GetTokens(EasyScriptParser.SPACE); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode SPACE(int i) {
			return GetToken(EasyScriptParser.SPACE, i);
		}
		public Expect_Context(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_expect_; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IEasyScriptListener typedListener = listener as IEasyScriptListener;
			if (typedListener != null) typedListener.EnterExpect_(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IEasyScriptListener typedListener = listener as IEasyScriptListener;
			if (typedListener != null) typedListener.ExitExpect_(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IEasyScriptVisitor<TResult> typedVisitor = visitor as IEasyScriptVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitExpect_(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Expect_Context expect_() {
		Expect_Context _localctx = new Expect_Context(Context, State);
		EnterRule(_localctx, 10, RULE_expect_);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 53;
			Match(EXPECT_);
			State = 55;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			do {
				{
				{
				State = 54;
				Match(SPACE);
				}
				}
				State = 57;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			} while ( _la==SPACE );
			State = 59;
			_la = TokenStream.LA(1);
			if ( !((((_la) & ~0x3f) == 0 && ((1L << _la) & 448L) != 0)) ) {
			ErrorHandler.RecoverInline(this);
			}
			else {
				ErrorHandler.ReportMatch(this);
			    Consume();
			}
			State = 61;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			do {
				{
				{
				State = 60;
				Match(SPACE);
				}
				}
				State = 63;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			} while ( _la==SPACE );
			State = 65;
			unknownCommand();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Expect_error_Context : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode EXPECT_ERROR_() { return GetToken(EasyScriptParser.EXPECT_ERROR_, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public UnknownCommandContext unknownCommand() {
			return GetRuleContext<UnknownCommandContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode WORD() { return GetToken(EasyScriptParser.WORD, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode VARIABLE() { return GetToken(EasyScriptParser.VARIABLE, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode STRING() { return GetToken(EasyScriptParser.STRING, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] SPACE() { return GetTokens(EasyScriptParser.SPACE); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode SPACE(int i) {
			return GetToken(EasyScriptParser.SPACE, i);
		}
		public Expect_error_Context(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_expect_error_; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IEasyScriptListener typedListener = listener as IEasyScriptListener;
			if (typedListener != null) typedListener.EnterExpect_error_(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IEasyScriptListener typedListener = listener as IEasyScriptListener;
			if (typedListener != null) typedListener.ExitExpect_error_(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IEasyScriptVisitor<TResult> typedVisitor = visitor as IEasyScriptVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitExpect_error_(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Expect_error_Context expect_error_() {
		Expect_error_Context _localctx = new Expect_error_Context(Context, State);
		EnterRule(_localctx, 12, RULE_expect_error_);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 67;
			Match(EXPECT_ERROR_);
			State = 69;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			do {
				{
				{
				State = 68;
				Match(SPACE);
				}
				}
				State = 71;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			} while ( _la==SPACE );
			State = 73;
			_la = TokenStream.LA(1);
			if ( !((((_la) & ~0x3f) == 0 && ((1L << _la) & 448L) != 0)) ) {
			ErrorHandler.RecoverInline(this);
			}
			else {
				ErrorHandler.ReportMatch(this);
			    Consume();
			}
			State = 75;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			do {
				{
				{
				State = 74;
				Match(SPACE);
				}
				}
				State = 77;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			} while ( _la==SPACE );
			State = 79;
			unknownCommand();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class UnknownCommandContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode WORD() { return GetToken(EasyScriptParser.WORD, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ArgumentListContext argumentList() {
			return GetRuleContext<ArgumentListContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] SPACE() { return GetTokens(EasyScriptParser.SPACE); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode SPACE(int i) {
			return GetToken(EasyScriptParser.SPACE, i);
		}
		public UnknownCommandContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_unknownCommand; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IEasyScriptListener typedListener = listener as IEasyScriptListener;
			if (typedListener != null) typedListener.EnterUnknownCommand(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IEasyScriptListener typedListener = listener as IEasyScriptListener;
			if (typedListener != null) typedListener.ExitUnknownCommand(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IEasyScriptVisitor<TResult> typedVisitor = visitor as IEasyScriptVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitUnknownCommand(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public UnknownCommandContext unknownCommand() {
		UnknownCommandContext _localctx = new UnknownCommandContext(Context, State);
		EnterRule(_localctx, 14, RULE_unknownCommand);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 81;
			Match(WORD);
			State = 88;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==SPACE) {
				{
				State = 83;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				do {
					{
					{
					State = 82;
					Match(SPACE);
					}
					}
					State = 85;
					ErrorHandler.Sync(this);
					_la = TokenStream.LA(1);
				} while ( _la==SPACE );
				State = 87;
				argumentList();
				}
			}

			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class AssignmentContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode WORD() { return GetToken(EasyScriptParser.WORD, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode EQUAL() { return GetToken(EasyScriptParser.EQUAL, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public UnknownCommandContext unknownCommand() {
			return GetRuleContext<UnknownCommandContext>(0);
		}
		public AssignmentContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_assignment; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IEasyScriptListener typedListener = listener as IEasyScriptListener;
			if (typedListener != null) typedListener.EnterAssignment(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IEasyScriptListener typedListener = listener as IEasyScriptListener;
			if (typedListener != null) typedListener.ExitAssignment(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IEasyScriptVisitor<TResult> typedVisitor = visitor as IEasyScriptVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitAssignment(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public AssignmentContext assignment() {
		AssignmentContext _localctx = new AssignmentContext(Context, State);
		EnterRule(_localctx, 16, RULE_assignment);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 90;
			Match(WORD);
			State = 91;
			Match(EQUAL);
			State = 92;
			unknownCommand();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ArgumentListContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ArgumentContext argument() {
			return GetRuleContext<ArgumentContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ArgumentListContext argumentList() {
			return GetRuleContext<ArgumentListContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] SPACE() { return GetTokens(EasyScriptParser.SPACE); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode SPACE(int i) {
			return GetToken(EasyScriptParser.SPACE, i);
		}
		public ArgumentListContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_argumentList; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IEasyScriptListener typedListener = listener as IEasyScriptListener;
			if (typedListener != null) typedListener.EnterArgumentList(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IEasyScriptListener typedListener = listener as IEasyScriptListener;
			if (typedListener != null) typedListener.ExitArgumentList(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IEasyScriptVisitor<TResult> typedVisitor = visitor as IEasyScriptVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitArgumentList(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ArgumentListContext argumentList() {
		ArgumentListContext _localctx = new ArgumentListContext(Context, State);
		EnterRule(_localctx, 18, RULE_argumentList);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 94;
			argument();
			State = 101;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==SPACE) {
				{
				State = 96;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				do {
					{
					{
					State = 95;
					Match(SPACE);
					}
					}
					State = 98;
					ErrorHandler.Sync(this);
					_la = TokenStream.LA(1);
				} while ( _la==SPACE );
				State = 100;
				argumentList();
				}
			}

			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ArgumentContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] WORD() { return GetTokens(EasyScriptParser.WORD); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode WORD(int i) {
			return GetToken(EasyScriptParser.WORD, i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode EQUAL() { return GetToken(EasyScriptParser.EQUAL, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode VARIABLE() { return GetToken(EasyScriptParser.VARIABLE, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode STRING() { return GetToken(EasyScriptParser.STRING, 0); }
		public ArgumentContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_argument; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IEasyScriptListener typedListener = listener as IEasyScriptListener;
			if (typedListener != null) typedListener.EnterArgument(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IEasyScriptListener typedListener = listener as IEasyScriptListener;
			if (typedListener != null) typedListener.ExitArgument(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IEasyScriptVisitor<TResult> typedVisitor = visitor as IEasyScriptVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitArgument(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ArgumentContext argument() {
		ArgumentContext _localctx = new ArgumentContext(Context, State);
		EnterRule(_localctx, 20, RULE_argument);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 103;
			Match(WORD);
			State = 104;
			Match(EQUAL);
			State = 105;
			_la = TokenStream.LA(1);
			if ( !((((_la) & ~0x3f) == 0 && ((1L << _la) & 448L) != 0)) ) {
			ErrorHandler.RecoverInline(this);
			}
			else {
				ErrorHandler.ReportMatch(this);
			    Consume();
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	private static int[] _serializedATN = {
		4,1,11,108,2,0,7,0,2,1,7,1,2,2,7,2,2,3,7,3,2,4,7,4,2,5,7,5,2,6,7,6,2,7,
		7,7,2,8,7,8,2,9,7,9,2,10,7,10,1,0,1,0,5,0,25,8,0,10,0,12,0,28,9,0,1,0,
		3,0,31,8,0,1,1,1,1,1,1,1,2,1,2,1,2,1,2,1,2,1,2,3,2,42,8,2,1,3,1,3,4,3,
		46,8,3,11,3,12,3,47,1,3,1,3,1,4,1,4,1,5,1,5,4,5,56,8,5,11,5,12,5,57,1,
		5,1,5,4,5,62,8,5,11,5,12,5,63,1,5,1,5,1,6,1,6,4,6,70,8,6,11,6,12,6,71,
		1,6,1,6,4,6,76,8,6,11,6,12,6,77,1,6,1,6,1,7,1,7,4,7,84,8,7,11,7,12,7,85,
		1,7,3,7,89,8,7,1,8,1,8,1,8,1,8,1,9,1,9,4,9,97,8,9,11,9,12,9,98,1,9,3,9,
		102,8,9,1,10,1,10,1,10,1,10,1,10,0,0,11,0,2,4,6,8,10,12,14,16,18,20,0,
		2,1,1,9,9,1,0,6,8,113,0,26,1,0,0,0,2,32,1,0,0,0,4,41,1,0,0,0,6,43,1,0,
		0,0,8,51,1,0,0,0,10,53,1,0,0,0,12,67,1,0,0,0,14,81,1,0,0,0,16,90,1,0,0,
		0,18,94,1,0,0,0,20,103,1,0,0,0,22,25,3,2,1,0,23,25,5,9,0,0,24,22,1,0,0,
		0,24,23,1,0,0,0,25,28,1,0,0,0,26,24,1,0,0,0,26,27,1,0,0,0,27,30,1,0,0,
		0,28,26,1,0,0,0,29,31,5,0,0,1,30,29,1,0,0,0,30,31,1,0,0,0,31,1,1,0,0,0,
		32,33,3,4,2,0,33,34,7,0,0,0,34,3,1,0,0,0,35,42,3,6,3,0,36,42,3,8,4,0,37,
		42,3,10,5,0,38,42,3,12,6,0,39,42,3,14,7,0,40,42,3,16,8,0,41,35,1,0,0,0,
		41,36,1,0,0,0,41,37,1,0,0,0,41,38,1,0,0,0,41,39,1,0,0,0,41,40,1,0,0,0,
		42,5,1,0,0,0,43,45,5,2,0,0,44,46,5,10,0,0,45,44,1,0,0,0,46,47,1,0,0,0,
		47,45,1,0,0,0,47,48,1,0,0,0,48,49,1,0,0,0,49,50,7,1,0,0,50,7,1,0,0,0,51,
		52,5,3,0,0,52,9,1,0,0,0,53,55,5,4,0,0,54,56,5,10,0,0,55,54,1,0,0,0,56,
		57,1,0,0,0,57,55,1,0,0,0,57,58,1,0,0,0,58,59,1,0,0,0,59,61,7,1,0,0,60,
		62,5,10,0,0,61,60,1,0,0,0,62,63,1,0,0,0,63,61,1,0,0,0,63,64,1,0,0,0,64,
		65,1,0,0,0,65,66,3,14,7,0,66,11,1,0,0,0,67,69,5,5,0,0,68,70,5,10,0,0,69,
		68,1,0,0,0,70,71,1,0,0,0,71,69,1,0,0,0,71,72,1,0,0,0,72,73,1,0,0,0,73,
		75,7,1,0,0,74,76,5,10,0,0,75,74,1,0,0,0,76,77,1,0,0,0,77,75,1,0,0,0,77,
		78,1,0,0,0,78,79,1,0,0,0,79,80,3,14,7,0,80,13,1,0,0,0,81,88,5,6,0,0,82,
		84,5,10,0,0,83,82,1,0,0,0,84,85,1,0,0,0,85,83,1,0,0,0,85,86,1,0,0,0,86,
		87,1,0,0,0,87,89,3,18,9,0,88,83,1,0,0,0,88,89,1,0,0,0,89,15,1,0,0,0,90,
		91,5,6,0,0,91,92,5,1,0,0,92,93,3,14,7,0,93,17,1,0,0,0,94,101,3,20,10,0,
		95,97,5,10,0,0,96,95,1,0,0,0,97,98,1,0,0,0,98,96,1,0,0,0,98,99,1,0,0,0,
		99,100,1,0,0,0,100,102,3,18,9,0,101,96,1,0,0,0,101,102,1,0,0,0,102,19,
		1,0,0,0,103,104,5,6,0,0,104,105,5,1,0,0,105,106,7,1,0,0,106,21,1,0,0,0,
		13,24,26,30,41,47,57,63,71,77,85,88,98,101
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
} // namespace EasyAccept.Core.Grammar
